package com.podcast.reader.tts

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import android.content.Context
import java.io.File
import java.nio.FloatBuffer

/**
 * Kokoro engine over ONNX Runtime Mobile.
 *
 * EXPECTS:
 *   assets/kokoro/kokoro_int8.ort         — the quantized model
 *   assets/kokoro/voices/<voice>.bin      — voice embedding tables
 *
 * Generated by `scripts/convert_kokoro_to_onnx.py` (must be run on a machine
 * with PyTorch + the kokoro Python package + the float weights from
 * `models/Kokoro-82M/kokoro-v1_0.pth`).
 *
 * If the model asset is missing, [load] throws EngineNotReadyException with
 * reason="model_path_missing" so the UI can prompt the user to side-load it.
 */
class KokoroOnnxEngine(private val context: Context) : Engine {
    override val name: String = "kokoro"
    private var environment: OrtEnvironment? = null
    private var session: OrtSession? = null
    @Volatile private var loaded: Boolean = false
    override val isLoaded: Boolean get() = loaded

    private val sampleRate = 24000

    override suspend fun load() {
        if (loaded) return
        val modelFile = stageAsset(MODEL_ASSET)
            ?: throw EngineNotReadyException(
                reason = "model_path_missing",
                message = "Kokoro ONNX model not found in app assets",
                paths = listOf(MODEL_ASSET),
            )
        val env = OrtEnvironment.getEnvironment()
        val opts = OrtSession.SessionOptions().apply {
            setIntraOpNumThreads(2)
            setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT)
        }
        session = env.createSession(modelFile.absolutePath, opts)
        environment = env
        loaded = true
    }

    override suspend fun unload() {
        session?.close()
        session = null
        environment = null
        loaded = false
    }

    override suspend fun synthesize(
        text: String,
        outFile: File,
        voice: String,
        language: String,
        speed: Float,
    ): Long {
        if (!loaded) load()
        val sess = session ?: error("session not initialized")
        val env = environment ?: error("env not initialized")

        // Phase-2 scaffold: real Kokoro ONNX export requires a tokenizer +
        // voice-embedding lookup. The contract below is what the conversion
        // script in scripts/convert_kokoro_to_onnx.py is expected to produce:
        //
        //   inputs:
        //     tokens     : int64[seq_len]
        //     voice      : float[256]      (style vector for the chosen voice)
        //     speed      : float[1]
        //   outputs:
        //     audio      : float[n_samples] in [-1.0, 1.0] at 24kHz mono.
        //
        // We provide a deterministic placeholder tokenizer so the wiring is
        // exercised even before the real ONNX model lands.
        val tokens = naiveTokenize(text)
        val voiceVec = loadVoiceEmbedding(voice)
        val tokenLongs = LongArray(tokens.size) { tokens[it].toLong() }
        val tokenTensor = OnnxTensor.createTensor(
            env,
            java.nio.LongBuffer.wrap(tokenLongs),
            longArrayOf(tokenLongs.size.toLong()),
        )
        val voiceTensor = OnnxTensor.createTensor(
            env,
            FloatBuffer.wrap(voiceVec),
            longArrayOf(voiceVec.size.toLong()),
        )
        val speedTensor = OnnxTensor.createTensor(
            env,
            FloatBuffer.wrap(floatArrayOf(speed)),
            longArrayOf(1),
        )

        val inputs = mapOf("tokens" to tokenTensor, "voice" to voiceTensor, "speed" to speedTensor)
        sess.run(inputs).use { result ->
            val raw = result[0].value as Array<FloatArray>
            val flat = raw[0]
            val pcm = ShortArray(flat.size) { i ->
                (flat[i].coerceIn(-1.0f, 1.0f) * 32767f).toInt().toShort()
            }
            StubEngine.writeWav(outFile, pcm, sampleRate)
            return (pcm.size * 1000L) / sampleRate
        }
    }

    private fun stageAsset(name: String): File? {
        val cached = File(context.cacheDir, name)
        if (cached.exists() && cached.length() > 0) return cached
        return runCatching {
            context.assets.open(name).use { input ->
                cached.parentFile?.mkdirs()
                cached.outputStream().use { input.copyTo(it) }
            }
            cached
        }.getOrNull()
    }

    private fun loadVoiceEmbedding(voice: String): FloatArray {
        val assetPath = "kokoro/voices/$voice.bin"
        return runCatching {
            context.assets.open(assetPath).use { input ->
                val bytes = input.readBytes()
                val fb = java.nio.ByteBuffer.wrap(bytes).order(java.nio.ByteOrder.LITTLE_ENDIAN).asFloatBuffer()
                FloatArray(fb.remaining()).also { fb.get(it) }
            }
        }.getOrElse {
            // Fall back to a zero vector; the model will still produce something,
            // just without a specific voice character.
            FloatArray(256)
        }
    }

    /**
     * Placeholder tokenizer until the real Kokoro phoneme tokenizer is wired up.
     * The conversion script is responsible for producing a model variant whose
     * tokenizer matches what we put here.
     */
    private fun naiveTokenize(text: String): IntArray {
        val codepoints = text.codePoints().toArray()
        return IntArray(codepoints.size) { i -> (codepoints[i] and 0x7F).coerceIn(1, 127) }
    }

    companion object {
        private const val MODEL_ASSET = "kokoro/kokoro_int8.ort"
    }
}
